In [ ]:
#  numpy array module is used for creating arrays
#  numpy arrays are faster than python lists

# properties of arrays
# 1. all elements of numpy array must be of same type
# 2. elements of an array are located at contiguous memory locations
# 3. each element of an array can be accessed by its index

# types of arrays
# 1. 1D array
#    - an array with a bunch of values having been declared in a single index
#    - to access an element of a 1D array, we use its index: arr[0]  
# 2. multi-dimensional array
#    - an array with a bunch of values having been declared in multiple indexes
#    - to access an element of a multi-dimensional array, we use its index: arr[0][0]


In [29]:
from array import * 
import numpy as np


In [15]:
my_array = array.array('i', [1, 2, 3, 4, 5]) # i is the typecode for integer (O(1) time complexity)
print(my_array)

array('i', [1, 2, 3, 4, 5])


In [11]:
np_array = np.array([1, 2, 3, 4, 5])  # O(N) time complexity, space complexity is O(N)
print(np_array)

[1 2 3 4 5]


In [12]:
# insertion to an array
# 1. insert at the beginning of an array
# 2. insert at the end of an array
# 3. insert at a given index of an array



In [27]:
# 1. insert at the beginning of an array
#    - we need to shift all the elements of the array to the right by one index
#    - we need to increase the size of the array by one
#    - we need to insert the new element at the beginning of the array
#    - time complexity: O(N)
#    - space complexity: O(1)
#    - we can use the insert() method of the array module
#    - we can use the insert() method of the numpy module
my_array.insert(0, 7)
print(my_array)

array('i', [7, 1, 2, 3, 4, 5])


In [17]:
# array traversal 
# 1. traversal using for loop
# 2. traversal using while loop
#  time complexity: O(N)
#  space complexity: O(1)

def traverse_array(arr):
    for i in arr:
        print(i)

traverse_array(my_array)

7
1
2
3
4
5


In [21]:
#  access array elements
#  1. access an element at a given index
#  time complexity: O(1)
#  space complexity: O(1)

def accessElement(array, index):
    if index >= len(array):
        print("index is out of bounds")
    else:
        print(array[index])

accessElement(my_array, 6)
accessElement(my_array, 0)

index is out of bounds
7


In [24]:
# searching for an element in an array

# 1. linear search
#    - we traverse the array from left to right and compare each element with the given element
#    - if the element is found, we return the index of the element
#    - if the element is not found, we return some indicative message that element was not found: -1

#  time complexity: O(N)
#  space complexity: O(1)

def linear_search(arr, element):
    for i in range(len(arr)):
        if arr[i] == element:
            return i
    return -1

print(linear_search(my_array, 8))
print(linear_search(my_array, 7))


-1
0


In [28]:
#  deletion from an array
#  1. delete from the beginning of an array
#  2. delete from the end of an array
#  3. delete from a given index of an array

# time complexity: O(N)
# space complexity: O(1)

my_array.remove(7)
print(my_array)

array('i', [1, 2, 3, 4, 5])


In [40]:
my_array = array('i', [1, 2, 3, 4, 5])

for i in my_array:
    print(i)

1
2
3
4
5


In [41]:
my_array[4]

5

In [42]:
my_array.append(6)
my_array


array('i', [1, 2, 3, 4, 5, 6])

In [43]:
my_array.insert(6, 7)
my_array

array('i', [1, 2, 3, 4, 5, 6, 7])

In [44]:
my_array1 = array('i', [10, 11, 12, 13, 14])
my_array.extend(my_array1)
my_array

array('i', [1, 2, 3, 4, 5, 6, 7, 10, 11, 12, 13, 14])

In [45]:
templist = [20, 21, 22]
my_array.fromlist(templist)
my_array

array('i', [1, 2, 3, 4, 5, 6, 7, 10, 11, 12, 13, 14, 20, 21, 22])

In [46]:
my_array.pop()
my_array

array('i', [1, 2, 3, 4, 5, 6, 7, 10, 11, 12, 13, 14, 20, 21])

In [47]:
my_array.index(11)

8

In [48]:
my_array.reverse()
my_array

array('i', [21, 20, 14, 13, 12, 11, 10, 7, 6, 5, 4, 3, 2, 1])

In [50]:
my_array.buffer_info()


(1331784577264, 14)

In [51]:
my_array.count(11)

1

In [56]:
twoD_array = np.array([[11, 15, 10, 6], [10, 14, 11, 5], [12, 17, 12, 8], [15, 18, 14, 9],])
twoD_array

array([[11, 15, 10,  6],
       [10, 14, 11,  5],
       [12, 17, 12,  8],
       [15, 18, 14,  9]])

In [73]:
#  insertion - two dimensional array
#  1. insert at the beginning of a two dimensional array

#  time complexity: O(mn)

new_twoD_array = twoD_array = np.insert(twoD_array, 0, [[1, 2, 3, 4]], axis=0)
new_twoD_array

array([[ 1,  2,  3,  4],
       [ 1,  2,  3,  4],
       [11, 15, 10,  6],
       [10, 14, 11,  5],
       [12, 17, 12,  8],
       [15, 18, 14,  9]])

In [72]:
twoD_array2 = np.append(twoD_array, [[1, 2, 3, 4]], axis=0)
twoD_array2

array([[ 1,  2,  3,  4],
       [11, 15, 10,  6],
       [10, 14, 11,  5],
       [12, 17, 12,  8],
       [15, 18, 14,  9],
       [ 1,  2,  3,  4]])

In [74]:
# access elements of a two dimensional array

# a[i]][j] - i is the row and j is the column index 

def accessElement1(array, rowIndex, colIndex): 
    if rowIndex >= len(array) or colIndex >= len(array[0]):
        print("index is out of bounds")
    else:
        print(array[rowIndex][colIndex])

accessElement1(twoD_array, 1, 2)

3


In [75]:
twoD_array

array([[ 1,  2,  3,  4],
       [ 1,  2,  3,  4],
       [11, 15, 10,  6],
       [10, 14, 11,  5],
       [12, 17, 12,  8],
       [15, 18, 14,  9]])

In [81]:
#  traversal of a two dimensional array

#  time complexity: O(n^2)
#  space complexity: O(1)

def traverse2DArray(array):
    for i in range(len(array)):
        for j in range(len(array[i])):
            print(array[i][j])

traverse2DArray(twoD_array)

1
2
3
4
1
2
3
4
11
15
10
6
10
14
11
5
12
17
12
8
15
18
14
9


In [82]:
# searching for an element in a two dimensional array 

#  time complexity: O(n^2)
#  space complexity: O(1)

def search2DArray(array, element):
    for i in range(len(array)):
        for j in range(len(array[i])):
            if array[i][j] == element:
                return [i, j]
    return "element not found"

search2DArray(twoD_array, 10)

[2, 2]

In [83]:
# deletion from a two dimensional array

#  time complexity: O(mn)
#  space complexity: O(mn)

new_twoD_array = np.delete(twoD_array, 0, axis=0)
new_twoD_array

array([[ 1,  2,  3,  4],
       [11, 15, 10,  6],
       [10, 14, 11,  5],
       [12, 17, 12,  8],
       [15, 18, 14,  9]])

In [ ]:
# when to use / avoid arrays

# use: 
# - to store multiple variables of same type
# - random access 

# not use:
# - same data type elements 
# - reserve memory 